### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kosssi** [coconauts/NotificationListener-cordova#1]
Hello @rephus 
I would like launch my app when user clear a notification it's possible ? with this plugin ?
Your plugin is only for notification created ?

Thanks,

**Comment by rephus** [comment]
Hi @kosssi . 

This plugin listens to all notifications (once you give permissions on Android), once a notification is triggered you can do whatever you like. However your `listener` service (the app that uses this plugin) must be running on background before any notification has been triggered if you want to catch it. Take a look at https://developer.android.com/reference/android/service/notification/NotificationListenerService.html to see how `notificationlistenerservice` works on Android.

**Comment by kosssi** [comment]
thanks @rephus
