### ISSUE TITLE
is possible use in ionic 3 ?

### ISSUE THREAD

**Issue by diogobsd** [coconauts/NotificationListener-cordova#12]

**Comment by diogobsd** [comment]
on ionic 3 i dont know use... can you show ionic3 code ? thankyou

**Comment by rephus** [comment]
Well, I'm afraid I don't know anything about ionic 3, so I can't help

**Comment by diogobsd** [comment]
thank you for this plugin, SOLVED !
Ex:
Download pluging zip and extract
Import the folder plugin to ionic cordova:
`ionic cordova plugin add NotificationListener-cordova-master`

Source code for home.ts WORKING !

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

declare var notificationListener;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {

    this.setNotificationListenerCallback();

  }

  setNotificationListenerCallback(){
    notificationListener.listen(function(n){
      alert("Received notification " + JSON.stringify(n) );
    }, function(e){
      setTimeout(this.setNotificationListenerCallback, 1000);
      alert("Notification Error " + e);
    });
  }

}

```
Compile and run
`ionic cordova build android`
Finish !

**Comment by rephus** [comment]
That's awesome, nice work!

**Comment by GabrielCalin** [comment]
Well, unfortunately it doesn't work for me in Ionic 4. It sometimes reads notifications, but seems random. For example, reads a notification when I pause music, but not when I skip to the next song. Even this is random, when I restart my app, it might also read when I skip to the next song or might not read anything at all.

EDIT: most of the notifications are ignored like this - probably a bug:
_Ignore notification from pkg com.spotify.music_
I will try to pull this and correct it, although I never developed a cordova plugin so I need to do some learning first :)
